INT-2041: Command flag option to force API transaction sync
taxjar/taxjar-magento2-extension pull request #213
Opened 2021-10-19 15:38 UTC by sethobey

### Context

Users have reached out regarding issues with syncing M2 transactions where the state of the order has changed, and those changes need to be reflected in the TaxJar service, but due to the comparison of a transaction's `updated_at `and `tj_salestax_last_sync` dates, the transaction will continue to be skipped.

Currently, the only acceptable workaround for this problem is for M2 administrators to manually modify date values in DB, which for a large number of transactions.

### Description

- Adds flag `-f|--force` to CLI command `taxjar:transaction:sync` ![image](https://user-images.githubusercontent.com/47947793/137945544-7790ac7c-7d8d-4b05-9fad-ddc69dc47653.png)

- Refactors methods `\Taxjar\SalesTax\Model\Transaction\Order::push()` and `\Taxjar\SalesTax\Model\Transaction\Refund::push()` to accept optional parameters for http method and force-flag option.
- Adds "Force" select element (and tooltip) to the TaxJar transaction sync form 
![image](https://user-images.githubusercontent.com/47947793/138459614-06e1b765-539a-46a5-94c8-bf1ec19f7152.png)

- Adds unit test coverage for `\Taxjar\SalesTax\Model\Transaction\Backfill::process()` with `force` feature

### Performance

This should not have much if any affect on current extension performance,  but should resolve an on-going customer issue.

### Testing

1. With TaxJar's transaction sync feature enabled, *place an order*, either as customer, or as admin on behalf of customer, then invoice and mark shipped as necessary to move order status to "complete".
2. Verify that the order transaction has been persisted to TaxJar.
3. In DB, manually modify a value on the order such as an address value, or the order's `created_at` value.
4. From extension UI, attempt to sync transactions WITHOUT force-flag enabled. (using a date range containing the order)
5. Observe values not updated in TaxJar.
6. From extension UI, attempt to sync transactions WITH force-flag enabled (again, with proper date range).
7. Observe values updated in TaxJar.

#### Versions

- [X] Magento 2.4
- [ ] Magento 2.3
- [ ] Magento 2.2
- [ ] Magento 2.1

- [X] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [X] PHP 7.x
- [ ] PHP 5.x

2021-10-20 22:20 UTC, dallendalton requested changes

2021-10-20 22:20 UTC, dallendalton commented on Model/Transaction/Refund.php
> +    protected function makeRequest(string $method): array
It appears that this makeRequest method and the handleError method are almost identical between the refund and order models. Would it be worth it to abstract them out of these classes and into the transaction model?

2021-10-20 22:20 UTC, dallendalton commented on Model/Transaction/Refund.php
> +            $this->push($retry);
I don't think this method call will work as intended now that the push method's signature has changed. I think it will need to be something like this:

$this->push($forced, $retry). 

We will probably need to carry through the forced flag into this method or make it a member variable. That way we still honor the original setting.

The same issue also exists in the handleError method on the order model.

2021-10-20 22:20 UTC, dallendalton commented on Block/Adminhtml/TransactionSync/Form.php
> +        $fieldset->addField(
Could we add a more details description to this field? I don't know if it will be clear to most customers what the functionality of the force option does.

2021-10-20 22:20 UTC, dallendalton commented on Observer/BackfillTransactions.php
> +                'force' => $observer->getData('force'),
When doing the backfill from the UI, the force field on the operation is always set to null. In my testing this occurred when the field is both checked and unchecked. This causes a TypeError to be thrown down the line as it is not a boolean.

2021-10-20 23:22 UTC, dallendalton commented
Also, it appears as if the logging isn't functioning properly. After running the backfill here is the log entries I am seeing for an order:

20 Oct 2021 22:45:44 - Pushing order #%s: %s
20 Oct 2021 22:45:44 - [API] Order #%s saved to TaxJar: %s

Where this is what it looks like currently (when using the develop branch):
23 Aug 2021 19:06:18 - [PUT] Pushing order #000000004: {"plugin":"magento","provider":"api","transaction_id":"000000004","transaction_date":"2021-08-23T19:00:35+0000","amount":100,"shipping":0,"sales_tax":7.25,"from_country":"US","from_zip":"84651","from_state":"UT","from_city":"Payson","from_street":"123 Main St","to_country":"US","to_zip":"84651","to_state":"UT","to_city":"payson","to_street":"123 main st","line_items":[{"id":"5","quantity":1,"product_identifier":"Configurable-Black","description":"Configurable","unit_price":100,"discount":0,"sales_tax":7.25,"product_tax_code":""}]}
23 Aug 2021 19:06:18 - [API] Order #000000004 updated in TaxJar: {"order":{"user_id":104920,"transaction_reference_id":null,"transaction_id":"000000004","transaction_date":"2021-08-23T19:00:35.000Z","to_zip":"84651","to_street":"123 main st","to_state":"UT","to_country":"US","to_city":"PAYSON","shipping":"0.0","sales_tax":"7.25","provider":"api","line_items":[{"unit_price":"100.0","sales_tax":"7.25","quantity":1,"product_tax_code":null,"product_identifier":"Configurable-Black","id":0,"discount":"0.0","description":"Configurable"}],"from_zip":"84651","from_street":"123 Main St","from_state":"UT","from_country":"US","from_city":"PAYSON","exemption_type":null,"customer_id":null,"amount":"100.0"}}

2021-10-21 03:24 UTC, sethobey commented on Model/Transaction/Refund.php
> +            $this->push($retry);
Wow, great catch. I made a stupid git error right before I pushed this PR.  I thought that I had recovered everything properly in the IDE, but obviously not..

2021-10-21 03:25 UTC, sethobey commented on Model/Transaction/Refund.php
> +    protected function makeRequest(string $method): array
I agree with that as well, which is why I'm doing that in INT-1942 currently. I wanted to wait for that ticket since it seemed like it would touch these classes more.

2021-10-21 03:27 UTC, sethobey commented on Block/Adminhtml/TransactionSync/Form.php
> +        $fieldset->addField(
Sure thing, I think thats a good call out

2021-10-22 00:23 UTC, sethobey commented on Block/Adminhtml/TransactionSync/Form.php
> +        $fieldset->addField(
So in response to your feedback, I decided on two things:
1. To address the primary issue of ambiguity, I've added a hoverable tooltip following the form field in the adminhtml UI that describes the feature.
2. I think it kind of touches on ambiguity a bit, but also just provides a safer UI, so I changed the checkbox to a select element instead with declarative options "No" and "Yes". I think it is more inline with current UI than my original decision and might help prevent some situations where a customer accidentally engages with the form element esp. on touch devices like mobile.

<img width="1320" alt="Screen Shot 2021-10-21 at 7 11 28 PM" src="https://user-images.githubusercontent.com/47947793/138374045-891fa60d-5e51-4b03-b9d6-59283df2b0b8.png">

2021-10-22 00:23 UTC, sethobey commented on Observer/BackfillTransactions.php
> +                'force' => $observer->getData('force'),
✅

2021-10-22 00:53 UTC, sethobey commented
And log message string template errors are corrected also

[transaction.log.txt](https://github.com/taxjar/taxjar-magento2-extension/files/7393580/transaction.log.txt)

2021-10-26 19:33 UTC, dallendalton submitted a review, later dismissed

2021-10-26 19:33 UTC, dallendalton commented on Model/Transaction/Backfill.php
> +            [$orderIds, $forceFlag] = $this->getOperationData($operation);
There is still an issue with the force flag. Now I correctly see that the force flag is being set to 0 when the operation is created in BackfillTransactions.php. However here when it is getting the deserialized data from the operation is getting the string "0". Which causes a type error in the order push method as it is expecting a boolean.

2021-10-27 20:16 UTC, dallendalton requested changes

2021-10-27 20:16 UTC, dallendalton commented on Model/Transaction/Order.php
>              $this->originalOrder->setData('tj_salestax_sync_date', gmdate('Y-m-d H:i:s'))->save();
When running transaction backfill, after the order is synced it updates the sync timestamp. This triggers our extension to immediately try and sync it again. While our validation around updated at and sync at stops the second sync from triggering and API request it still clutters the logs and is not ideal. I wonder if there is a way we can still update the sync timestamp but not trigger the event/observer that causes the synchronous sync.

2021-10-27 20:16 UTC, dallendalton commented on Model/Transaction/Backfill.php
>                  $creditMemos = $order->getCreditmemosCollection();
This line appears not be working as intended. I tested by triggering the transaction sync through the UI without the force option enabled. 

When it gets to this line it doesn't find any creditMemos for the order. I tested on the develop branch using the same date range and it correctly found all the creditMemos for the orders selected. I'm not really sure what is causing the difference though.

2021-10-27 22:54 UTC, sethobey commented
> And log message string template errors are corrected also
> 
> [transaction.log.txt](https://github.com/taxjar/taxjar-magento2-extension/files/7393580/transaction.log.txt)

@dallendalton Taking a look in this log now, I see those `[SKIP]` entries hiding in there from the order-save event re-triggering

2021-10-27 23:07 UTC, sethobey commented on Model/Transaction/Order.php
>              $this->originalOrder->setData('tj_salestax_sync_date', gmdate('Y-m-d H:i:s'))->save();
This is resolved by refactoring to only save only the attribute, instead of the model (like in Refund class), bypassing the model saved event

2021-10-29 17:39 UTC, dallendalton approved these changes
One minor typo, but other than that looks great.

2021-10-29 17:39 UTC, dallendalton commented on Model/Transaction/Refund.php
> +     * exists of PUTing a resource that has not been created yet.
Minor typo in the comment here, should be or instead of of I think.

2021-10-29 19:36 UTC, sethobey commented on Model/Transaction/Refund.php
> +     * exists of PUTing a resource that has not been created yet.
🦅 👀

2021-10-29 20:01 UTC, jordan-k-johnson approved these changes
LGTM

2021-10-29 20:28 UTC, merged