XC-7: Sales Order Calculation Status - Metadata entity
taxjar/taxjar-magento2-extension pull request #234
Opened 2022-01-10 15:22 UTC by sethobey

### Context

WIP

### Description

### Performance

### Testing

1. [First Step]
2. [Second Step]
3. [and so on...]

#### Versions

- [ ] Magento 2.4
- [ ] Magento 2.3

- [ ] Magento Open Source (CE)
- [ ] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [ ] PHP 7.x

2022-01-10 15:24 UTC, sethobey commented on Api/Client/ClientInterface.php
> -declare(strict_types=1);
Found this typo I made in a previous implementation.. Strict types declaration only affects function CALLS not function DEFINITIONS so strict types should not be included in interface definitions.

2022-01-11 01:21 UTC, jordan-k-johnson approved these changes

2022-01-11 18:11 UTC, dallendalton requested changes

2022-01-11 18:11 UTC, dallendalton commented on Setup/UpgradeSchema.php
> +use Taxjar\SalesTax\Model\ResourceModel\OrderMetadata;
I'm getting the following error when I run setup:upgrade:

```
Fatal error: Uncaught Error: Class 'Taxjar\SalesTax\Model\ResourceModel\OrderMetadata' not found in /var/www/html/app/code/Taxjar/SalesTax/Setup/UpgradeSchema.php:188
Stack trace:
#0 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(1059): Taxjar\SalesTax\Setup\UpgradeSchema->upgrade(Object(Magento\Setup\Module\Setup), Object(Magento\Setup\Model\ModuleContext))
#1 /var/www/html/setup/src/Magento/Setup/Model/Installer.php(895): Magento\Setup\Model\Installer->handleDBSchemaData(Object(Magento\Setup\Module\Setup), 'schema', Array)
#2 /var/www/html/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php(146): Magento\Setup\Model\Installer->installSchema(Array)
#3 /var/www/html/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\UpgradeCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component in /var/www/html/app/code/Taxjar/SalesTax/Setup/UpgradeSchema.php on line 188
```
I think these paths might just need to be updated.

2022-01-11 18:24 UTC, sethobey commented on Setup/UpgradeSchema.php
> +use Taxjar\SalesTax\Model\ResourceModel\OrderMetadata;
Ahh, sorry! Bad rename.. Fixed!

2022-01-12 16:53 UTC, dallendalton approved these changes

2022-01-12 19:15 UTC, merged